---
- hosts: all
  remote_user: root
  tasks:
  - name: import glusterfs key
    apt_key:
      url: http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/pub.key
      state: present
    
  - name: ensure glusterfs repo is added
    apt_repository:
      repo: deb http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/Debian/jessie/apt jessie main
      state: present

  - name: install the latest package
    apt:
      update_cache: yes
      name: glusterfs-server
