---
- hosts: all
  remote_user: root
  tasks:
  - name: import the OpenNebula repo key
    apt_key:
      url: http://downloads.opennebula.org/repo/Debian/repo.key
      state: present

  - name: add the OpenNebula repo for Debian Stable
    apt_repository:
      repo: deb http://downloads.opennebula.org/repo/4.14/Debian/8 stable opennebula
      state: present
  - name: install required packages
    apt:
      update_cache: yes
      name: opennebula,opennebula-sunstone

  - name: disable strict host key checking
    shell: sudo -u oneadmin bash -c "echo -e \"Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n\" > /var/lib/one/.ssh/config" && chmod 600 /var/lib/one/.ssh/config
